[[plugins]]
    package = "./plugins/usercache"

[functions]
directory = "functions"
node_bundler = "esbuild"
included_files = ["prince", "prince-engine/**", "contrib/**", "fonts/**", "lib/**", "etc/**"]

[build]
command = "hugo -b $URL"
publish = "public/"
NODE_VERSION = "16.13.1"

[context.production]
command = "make production"

[build.environment]
HUGO_VERSION = "0.92.2"
HUGO_ENV = "development"
AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"

[context.production.environment]
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildDrafts -F"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildDrafts -F"

[dev]
command =  "make -j 10 dev"
framework = "#static"
publish = "./public/"
